Add Image Resizing
mlucy/basilica-client pull request #3
Opened 2019-02-04 20:23 UTC by thejsj

2019-02-05 04:48 UTC, mlucy requested changes
Some toplevel comments:

* After some though, I think we should actually resize to 512x512.  The network costs aren't that much larger, and if we deploy a newer image model it will probably want 512x512 input since that's becoming more common, and it would be nice if people didn't need to update their clients.
* I think there should be an option to turn off the automatic image resizing, just so that it's user-controllable in some future case we aren't considering.  (We could probably skimp on documenting that for now.)
* The version needs to be bumped.  This requires editing `setup.py` and `README.rst`.

2019-02-05 04:48 UTC, mlucy commented on basilica/basilica/__init__.py
> +        if (type(images) == list):
This should work for all enumerables, not just lists.

2019-02-05 04:48 UTC, mlucy commented on basilica/basilica/__init__.py
> +            data = ({'img': base64.b64encode(img).decode('utf-8')} for img in images)
This is also being done on line 130.  I think we should delete lines 130-133 and write:
```
data = ({'img': base64.b64encode(self.__resize_image(img)).decode('utf-8')} for img in images)
```

2019-02-05 04:48 UTC, mlucy commented on basilica/basilica/__init__.py
> +                    yield self.__resize_image(f.read())
I don't think we need to do this here, it's already being done in `embed_images`.

2019-02-05 04:48 UTC, mlucy commented on basilica/basilica/__init__.py
> +        im = im.convert("RGB")
Why do we need to do this RGB conversion?

2019-02-05 04:48 UTC, mlucy commented on basilica/basilica/__init__.py
> +        im = Image.open(BytesIO(image))
What's the error behavior if someone tries to open an unsupported image type?

2019-02-05 04:49 UTC, mlucy commented
This looks good!  It's awesome that it's so straightforward.

2019-02-05 04:51 UTC, mlucy commented
Also, we should probably add some tests so that we don't accidentally break this.  (We currently don't have unit tests for the client, which is maybe a mistake, so we'd have to add them to the basilica-django tests :/.)

2019-02-07 22:09 UTC, thejsj commented on basilica/basilica/__init__.py
> +        im = im.convert("RGB")
If it's a PNG, it's rbga.

2019-02-08 18:03 UTC, merged